services:
  - type: web
    name: medbot
    runtime: docker
    plan: free
    branch: main
    rootDir: backend
    healthCheckPath: /
    envVars:
      - key: PINECONE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 5000
      - key: TRANSFORMERS_CACHE
        value: /tmp
      - key: HF_HOME
        value: /tmp
    autoDeploy: true
